version: "3.8"

services:

  frontend:
    build: ./client
    depends_on:
      - backend
    ports:
      - "8080:80"

  backend:
    build: ./server
    depends_on:
      - database
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_CONN: "host=database user=tracker password=trackerpass dbname=trackerdb port=5432"

  database:
    image: postgres:14.1-alpine3.15
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    expose:
#      - "5432"
    restart: always
    environment:
      POSTGRES_DB: trackerdb
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: trackerpass

volumes:
  data: {}
